name = "OMRuntimeExternalC"
uuid = "ada38df0-e20e-11ed-02f3-2b4b19c1ec8a"
authors = ["Adrian Pop <adrian.pop@liu.se"]
version = "0.0.1"

[deps]
CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
Inflate = "d25df0c9-e2be-5dd7-82c8-3ad0b3e990b9"
Tar = "a4e569a6-e804-4fa4-b0f3-eef7a1d5b13e"
TarIterators = "06456b94-f2fb-4c2e-911f-0795f0d2fb0a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
ZipFile = "a5390f91-8eb1-5f08-bee0-b1d1ffed6cea"

